### ISSUE TITLE
create replay downloader

### ISSUE THREAD

**Issue by ronaudinho** [ronaudinho/drt#1]

**Comment by RiskyFeryansyahP** [comment]
For getting the replay downloader, I suggest we use the OpenDota API to obtain the `replay_url` [you can check the documentation here](https://docs.opendota.com/#tag/matches%2Fpaths%2F~1matches~1%7Bmatch_id%7D%2Fget). The API returns the `replay_url` which we can use to download the replay file to Valve.

However, it seems that the OpenDota API requires a credit card to obtain an `API KEY`, and I don't currently have one
