### ISSUE TITLE
move implementation codes from `rsc`

### ISSUE THREAD

**Issue by ronaudinho** [ronaudinho/drt#11]
[rsc](https://github.com/ronaudinho/drt/tree/master/rsc) dir is intended for throwaway codes, we should move actual implementation codes somewhere else.

structure may look something like
```
|- ...
|- internal
  |- client -> for anything that talks to external party
    |- ...
  |- replay -> for replay parsing related codes
  |- ui -> for TUI related codes
  |- ...
|- ...
```

**Comment by RiskyFeryansyahP** [comment]
I will work on this issue 🚀
